erDiagram
    Attacken {
        string Name PK
        string Type
        int Damage
    }
    Pokemon {
        int ID PK
        string Name
        int Generation
        int Value
    }
    Angebot {
        int ID PK
    }
    User { 
        string Username PK
        string Password
    }

    Im_Team {
        int Level 
        string Sickname
        string Username FK
        int PokemonID FK
    }

    User ||--|| Im_Team : ""
    Pokemon }|--|| Im_Team : ""

    User ||--|{ Pokemon : im_team

    Angebot }|--|| User : angezeigt
    Angebot }|--|{ Pokemon : im_angebot
    Attacken }|--|{ Pokemon : hat

